#!/bin/sh
# postinst script for sonic-platform-nokia-IXR7220-H6-128
#
# see: dh_installdeb(1)

chmod a+x /usr/local/bin/h6_128_platform_init.sh
chmod a+x /usr/local/bin/bmc_network_init.sh
systemctl daemon-reload || true
systemctl enable h6_128_platform_init.service
systemctl start h6_128_platform_init.service
# Bind service activation to usb0 device unit; avoid eager start at package install.
systemctl enable bmc_network_init.service
udevadm control --reload-rules || true
udevadm trigger --subsystem-match=net || true
chmod a+x /usr/local/bin/ports_notify.py
systemctl enable ports_notify.service
systemctl start --no-block ports_notify.service
